executable              = test.sh

Requirements = HAS_SINGULARITY == TRUE
+SingularityImage = "/cvmfs/singularity.opensciencegrid.org/grassla/osg_testing:latest"

transfer_input_files    = test.py
transfer_output_files   = test.output

log                     = test.log
output                  = test.output
error                   = test.error

should_transfer_files   = Yes
when_to_transfer_output = ON_EXIT
queue 10
